// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybmdyqcjvuplybynatqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlibWR5cWNqdnVwbHlieW5hdHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NjI0NDAsImV4cCI6MjA1NTQzODQ0MH0.BprfWg3Dlidp5fgwOIXh2MJjhjNOPylmuvOx7G5HkAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);